### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by denar90**
Fix for #13

### CODE REVIEW

**Comment by jdaudier** [comment]
Thanks @denar90!

**Comment by jdaudier** [comment]
Travis is not happy though...

**Comment by denar90** [comment]
Yeah, need to fix build fails. I'll do it in scope of this PR)

**Comment by denar90** [comment]
sorry, accidentally created another one #17. Now travis is happy 😄 
@jdaudier can you take care of all this?

**Pull request closed without merging**
