### PR TITLE
use webpack-dev-server for dev experience

### PR DESCRIPTION
**Pull request by royling**
- Added `webpack-dev-server` which brings in live-reload feature
- Removed `http-server` dep
- Added `.editorconfig`
- Changed to use npm scripts only (removed `Makefile`)

### CODE REVIEW

**Comment by royling** [comment]
Do you mean to apply the config for all? need to copy it to target in `yo` command?

**Comment by denar90** [comment]
Yeah, I would like to.

**Comment by royling** [comment]
noted that `.eslintrc` and `.gitignore` are duplicated in each boilerplate. As my understanding, this is to support scaffolding without `yeoman` (directly get started from the boilerplate folder), right?

So is it OK to simply put `.editorconfig` file into each folder?
We could also move these template files to a folder and copy them in `generateApp` function, that will limit scaffolding to only `yo` command...

your thoughts?

**Comment by denar90** [comment]
Yeah, but `yo` is not released yet, so I think better for now just put it into top level (for people who wanna contribute) for now.

**Comment by royling** [comment]
`.editorconfig` is put in the top level and also _templates_ folder which will be generated to target in `yo` command.

**Pull request merged**
