### PR TITLE
Update marionette apps with different build tools

### PR DESCRIPTION
**Pull request by denar90**
I've added Mn with webpack, brunch, browserify.
Also I have some proposition to use submodules for webpack, brunch, browserify folders. It will be easy for people to start work with different build tools. Someone can just clone one of webpack, brunch, browserify and play without cloning `marionette-integrations` repo.

### CODE REVIEW

**Comment by samccone** [comment]
awesome! thanks @denar90

**Comment by denar90** [comment]
@samccone what do you think about using git submodules for webpack, brunch, browserify folders?

**Comment by samccone** [comment]
not worth the complexity overhead, nothing wrong with a mono-repo here

**Comment by denar90** [comment]
Rreason why I asked about it is about reusing subrepos for e.g. in Mn doc or guides. We will figure something out) 
Thanks for merging PR :smile:

**Pull request merged**
