### PR TITLE
add eslint

### PR DESCRIPTION
**Pull request by denar90**
Changes:
 - eslint added
 - folders with tests added to build

### CODE REVIEW

**Comment by jdaudier** [comment]
@denar90: looks like Travis is not happy

**Comment by denar90** [comment]
@jdaudier yeap, because we didn't merge #17 
Last time Travis is in a bad mood 😄

**Comment by jdaudier** [comment]
Thanks @denar90!

**Comment by jdaudier** [comment]
@denar90: Can you resolve the conflict?

**Comment by denar90** [comment]
JFYI. I removed `cypress` from build because it want's to have `Cypress` app to be installed. It's closed still, only small amount of people have it. It's about to be released.

**Comment by jdaudier** [comment]
@denar90 Thanks!

**Pull request merged**
